apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: promote-run-manual
spec:
  pipelineRef:
    name: ansible-lint-pipeline
  params:
    - name: git-url
      value: https://github.com/rrbanda/ansible-tekton.git
    - name: git-revision
      value: dev
    - name: target-repo-url
      value: https://github.com/rrbanda/ansible-tekton.git
    - name: pr-base-branch
      value: stage
    - name: auto-merge
      value: "true"
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: ansible-tekton-pvc
