apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: ansible-lint-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-dev-branch-trigger
      interceptors:
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.ref == 'refs/heads/dev'"
        - ref:
            name: "github"
        - ref:
            name: "cel"
          params:
            - name: "overlays"
              value:
                - key: branch
                  expression: "body.ref.split('/')[2]"
      bindings:
        - ref: ansible-lint-trigger-binding
      template:
        ref: ansible-lint-trigger-template
