apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: ansible-lint-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-listener
      interceptors:
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.ref == 'refs/heads/dev'"
      bindings:
        - ref: ansible-lint-trigger-binding
      template:
        ref: ansible-lint-trigger-template
