apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: ansible-lint-trigger-binding
spec:
  params:
    - name: git-url
      value: $(body.repository.clone_url)
    - name: git-revision
      value: $(body.ref)  # full ref, e.g., "refs/heads/dev"
