---
- name: Create a user with SSH key
  hosts: localhost
  become: true
  tasks:
    - name: Ensure user "devops" exists
      ansible.builtin.user:
        name: devops
        shell: /bin/bash

    - name: Set authorized key for devops
      ansible.builtin.authorized_key:
        user: devops
        state: present
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1fakedemokey1234567890 demo@localhost"
